//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_intelimundo
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_centro
    {
        public System.Guid id_centro { get; set; }
        public string id_codigo_centro { get; set; }
        public Nullable<int> id_tipo_centro { get; set; }
        public Nullable<int> id_estatus { get; set; }
        public int id_licencia { get; set; }
        public string nombre { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string cp { get; set; }
        public string calle { get; set; }
        public Nullable<int> id_asenta_cpcons { get; set; }
        public Nullable<System.DateTime> fecha_corte { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> dia_corte { get; set; }
    }
}
