//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_intelimundo
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_examenes_dep
    {
        public int id_examenes_desp { get; set; }
        public int id_pregunta_exam { get; set; }
        public int id_respuestas_exam { get; set; }
        public System.Guid id_examenes { get; set; }
    }
}
