//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_intelimundo
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inf_proveedor()
        {
            this.inf_contacto_proveedor = new HashSet<inf_contacto_proveedor>();
        }
    
        public System.Guid id_proveedor { get; set; }
        public Nullable<int> id_estatus { get; set; }
        public Nullable<int> id_tipo_rfc { get; set; }
        public string rfc { get; set; }
        public string razon_social { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string callenum { get; set; }
        public Nullable<int> id_codigo { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public System.Guid id_centro { get; set; }
    
        public virtual fact_estatus fact_estatus { get; set; }
        public virtual fact_tipo_rfc fact_tipo_rfc { get; set; }
        public virtual inf_centro inf_centro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_contacto_proveedor> inf_contacto_proveedor { get; set; }
        public virtual inf_sepomex inf_sepomex { get; set; }
    }
}
