//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_intelimundo
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_ventas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inf_ventas()
        {
            this.inf_ventas_dep = new HashSet<inf_ventas_dep>();
        }
    
        public System.Guid id_ventas { get; set; }
        public Nullable<int> id_estatus { get; set; }
        public string codigo_venta { get; set; }
        public Nullable<int> tipo_venta { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public System.Guid id_usuario { get; set; }
        public System.Guid id_alumno { get; set; }
        public System.Guid id_centro { get; set; }
    
        public virtual inf_centro inf_centro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_ventas_dep> inf_ventas_dep { get; set; }
    }
}
