//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_intelimundo
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_centro_dep
    {
        public int id_sucursal_dep { get; set; }
        public Nullable<System.Guid> id_usuario { get; set; }
        public Nullable<System.Guid> id_centro { get; set; }
    }
}
