//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_intelimundo
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_alumnos
    {
        public System.Guid id_alumno { get; set; }
        public string id_codigo_alumno { get; set; }
        public Nullable<int> id_estatus { get; set; }
        public Nullable<int> id_genero { get; set; }
        public Nullable<int> id_tipo_usuario { get; set; }
        public string nombres { get; set; }
        public string a_paterno { get; set; }
        public string a_materno { get; set; }
        public string codigo_alumno { get; set; }
        public string clave { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public System.Guid id_centro { get; set; }
    
        public virtual fact_estatus fact_estatus { get; set; }
        public virtual fact_genero fact_genero { get; set; }
        public virtual fact_tipo_usuario fact_tipo_usuario { get; set; }
        public virtual inf_centro inf_centro { get; set; }
    }
}
